dist: xenial xerus
sudo: required
language: python
python:
  - 3.5
script: 
- sudo wget https://raw.githubusercontent.com/sch00lb0y/yaydoc/master/generate.sh 
- sudo chmod +x ./generate.sh
- sudo apt-get update
- sudo pip install sphinx
- sudo sphinx-quickstart -h

